[package]
name = "453g2w4gdmavnsut"
version = "0.1.0"
authors = ["Christopher Monsanto <chris@monsan.to>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]